### ISSUE TITLE
@conda-forge-admin, please update team

### ISSUE THREAD

**Issue by wolfv** [conda-forge/ipypivot-feedstock#12]
cc @PierreMarion23

**Comment by PierreMarion23** [comment]
Thanks @wolfv, this looks like the good solution. Although it didn't seem to have any effect? The conda-forge bot didn't comment.

**Comment by wolfv** [comment]
I manually added the ipypivot team to this feedstock with write access. You are a member of that team, so everything should work now for you.

Cheers!
